### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by APWMSchrauwen** [fcsonline/node-telescope-server#4]
Hi,

Newbie here, so it might not be a problem to you.

When I try to connect with my LXD75 telescope with the lx200.js I got the following message:

nts -s stellarium -p 5000 -t lx200 -i /dev/ttyUSB0

/usr/local/lib/node_modules/node-telescope-server/telescopes/lx200.js:17
this.device.on("end", function () {
              ^
TypeError: Cannot call method 'on' of undefined
at new Telescope (/usr/local/lib/node_modules/node-telescope-server/telescop                                                                             es/lx200.js:17:15)
at createServer (/usr/local/lib/node_modules/node-telescope-server/bin/nts:2                                                                             9:19)
at Object.<anonymous> (/usr/local/lib/node_modules/node-telescope-server/bin                                                                             /nts:50:3)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:901:3
pi@raspberrypi ~ $

Do you have a solution? Nexstar and the dummy work fine.

Many thanks!

Best regards,

Arjan

**Comment by corentoulf** [comment]
Hi,

I'm facing the same issue. Did you find a solution ?
Thanks.

Corentin

**Comment by APWMSchrauwen** [comment]
Hi Corentin,

No, I didn't find a solution (yet). I went further with building other projects. In the next few months I will try again. If I find a solution or a workaround, I'll e-mail you.

Best regards,

Arjan

Verstuurd vanaf mijn iPad

**Comment by corentoulf** [comment]
Thanks for your feedback.

I'm still working on it, so, I'll also tell you if something runs well in the end.

Corenitn
